### ISSUE TITLE
backup missing /data/misc/keystore/user_0

### ISSUE THREAD

**Issue by TheRealDarklord** [mauronofrio/android_device_xiaomi_raphael#2]
Hi,

I just wanted to report that creating a backup with your TWRP build misses some crucial files from the keystore. I compare to TWRP backups from my OnePlus 2 device and there this folder is included in the data backup. There are some more folders but maybe this could be a difference between LOS and the MIUI ROM. The keystore should be part of the backup for certain.

The corresponding part in the recovery.log file says that some of the files from /data/misc/keystore/user_0 were copied to /tmp/misc/keystore/user_0 but they are not included in the backup.

Restoring this backup was not successful and I ended up setting up my device from a clean install :(

**Comment by mauronofrio** [comment]
This doesn't depend from me or my device tree but the Teamwin source, you should open there a issue fro this
